README.md
lib/cocoapods_plugin.rb
slather.gemspec
spec/slather/cocoapods_plugin_spec.rb

From CocoaPods 0.36 you will need to explicitly mark which plugins you want in your Podfile. So you will need something like the following in your Podfile.
```ruby
plugin 'slather'
```
Re: #29 /cc @neonichu 
---
@marklarr This also means we can provide metadata from the Podfile to the plugin hook, if we need to provide any configuration.
```ruby
plugin 'slather', :foo => :bar
```

[CocoaPods] Update to CocoaPods 0.36 plugin API

---

bin/slather
lib/slather/coverage_service/coveralls.rb
spec/slather/coverage_service/coveralls_spec.rb

I've added support for [CircleCI](https://circleci.com), a neat CI service we use at work and which I've increasingly been using for my own personal projects. Like Travis, they offer free build containers for FOSS projects.
[Here](https://circleci.com/gh/splinesoft/SSDataSources/9) is a sample CircleCI+slather build in [one of my projects](https://github.com/splinesoft/SSDataSources) using my slather fork. The slathering, yea, it doth verily slather, but the build does not show on Coveralls. I am wondering if this is because:
- The latest CircleCI build for this project is 9, but the latest Travis build is 334, and perhaps Coveralls enforces increasing build number order?
- A missing access token or some other authorization requirement?
- Something else?
I would appreciate any suggestions …

Add CircleCI support

---

README.md
lib/slather/coverage_service/coveralls.rb

The current log format, `%B`, pulls in both the commit subject and raw body. For a merge commit, this results in a message like this that actually references two commits:
> Merge pull request #49 from splinesoft/circle
>
> Switch to CircleCI
This changes the coveralls commit message to just the commit subject, resulting in a cleaner message:
> Merge pull request #49 from splinesoft/circle

Include only commit subject in coveralls message

---

slather.gemspec

Since CocoaPods 0.37 has been released, the used version of xcodeproj needs to be bumped to make the CP plugin usable/loadable again.

Update used versions of CP and xcodeproj

---

lib/slather/coverage_service/coveralls.rb
spec/slather/coverage_service/coveralls_spec.rb

CircleCI has some [new env variables](https://circleci.com/docs/environment-variables) that provide extra information when the build originates from a push to a fork of the repo. I've updated slather to take advantage of these variables when they are available.

[CircleCI] Added new ENV variables for repo forks

---

README.md
lib/slather/coverage_service/coveralls.rb
lib/slather/project.rb
spec/slather/coverage_service/coveralls_spec.rb
spec/slather/project_spec.rb

Note: this happens to me locally too, https://github.com/venmo/slather/issues/74
Re: https://github.com/venmo/slather/issues/68 - I've added support for using an ENV var to pass your token in. Called it Coverage so that it can fit the other providers too.

[ENV] Add support for passing the coveralls token via an env var

---

lib/slather/coverage_file.rb

Quick fix for this crash: 
```
/Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/coverage_file.rb:74:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
from /Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/coverage_file.rb:74:in `cleaned_gcov_data'
from /Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/coverage_file.rb:62:in `line_coverage_data'
from /Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/coverage_file.rb:97:in `num_lines_testable'
from /Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/coverage_file.rb:109:in `percentage_lines_tested'
from /Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/project.rb:57:in `each'
from /Library/Ruby/Gems/2.0.0/gems/slather-1.7.1/lib/slather/project.rb:57:in `max_by'
from …
```

Fix crash on invalid byte sequence in UTF-8

---

CHANGELOG.md
README.md
slather.gemspec
spec/slather/cocoapods_plugin_spec.rb

Hi there,
I fixed the following issues with cocoapods v0.38:
- updated dependencies `cocoapods` and `xcodeproj`
- changed usage of `cocoapods` plugin API which has changed in version `0.38.x`
Fixes issue #94

Fixed dependency conflict with CocoaPods v0.38

---

bin/slather
lib/slather/coverage_service/coveralls.rb

Hi, I'm experimenting with Buildkite and needed coveralls support, so have added this. I'm by no means a ruby expert though, so this might be too scrappy to accept. Happy to edit as required however if you would like to accept but you'd like changes first.

Add buildkite support to coveralls

---

README.md

The codecov bash uploader has the option to specify the file to upload https://github.com/codecov/codecov-bash/blob/master/codecov#L32
The example as is would have the bash uploader search for coverage files but if you specify where the cobertura report is output then you know which file to have codecov upload.

Make codecove example read the report output by slather

---

lib/slather/project.rb

Is the suggestion for `project.pbxproj` correct? I shouldn't be `project.xcodeproj` instead?

.xcodeproj instead of .pbxproj in error

---

lib/slather/version.rb
slather.gemspec

This fixes a conflict with Cocoapods 0.39.0.
Adds clarity to commit message from #106. Thanks for taking care of this @tarbrain !

Update xcodeproj to 0.28.0

---

lib/slather/coverage_service/html_output.rb

I took a pull request by @joshrlesch, and cleaned it up so it didn't add anything custom back in. Tested on our own CI Servers.
This copies all the resources necessary to render the HTML into the HTML directory. We need something like this so we can upload the HTML to a web server where other users can view it.
I amended his commit. It looks like it has a different id, so it shouldn't cause any conflicts even though I was mucking with Git history.

Making HTML directory self contained

---

bin/slather
lib/slather/project.rb
spec/slather/project_spec.rb

Makes it easier to select the right binary to consider for code coverage computation. Instead of having to pass the full path to your framework, you can just configure its basename and it will be found :sparkles:

Add `binary_basename` configuration option

---

.travis.yml

This tries to fix wrong coverage report for this gem itself by avoiding bundle gem source being counted in Coveralls.
https://coveralls.io/github/SlatherOrg/slather

Avoid specifying path for bundle

---

lib/slather/coverage_service/cobertura_xml_output.rb

I had to add the date dependency in order to make it work. Without I get:
<..>/cobertura_xml_output.rb:114:in `create_xml_report': uninitialized constant Slather::CoverageService::CoberturaXmlOutput::DateTime (NameError)
Call command was:
slather coverage --jenkins -x --output-directory .  MyProject.xcodeproj

Add date dependency

---

CHANGELOG.md
lib/slather/project.rb
spec/slather/project_spec.rb
spec/spec_helper.rb

Version `2.0.0` of this gem fails with the following error in my project
```
Slathering...
error: Failed to load coverage: No object file for requested architecture
Test Coverage: NaN%
Slathered
```
running with verbose flag generated the following output
```
Slathering...
Processing coverage file: /Users/guidomb/Library/Developer/Xcode/DerivedData/Syrmo-gaycqmnmsbrteuaehthyregbeoec/Build/Intermediates/CodeCoverage/Syrmo/Coverage.profdata
Against binary file: /Users/guidomb/Library/Developer/Xcode/DerivedData/RESideMenu-drntsirbvffjqvdnxrvriljshzty/Build/Products/Release-iphoneos/RESideMenu.framework/RESideMenu
error: Failed to load coverage: No object file for requested architecture
Test Coverage: NaN%
Slathered
```
As it can be seen the binary file was pointing to another project (a …

Fixes how profdata_coverage_dir is created.

---

.gitignore
CHANGELOG.md
README.md
bin/slather
lib/slather/coverage_service/simple_output.rb
spec/slather/coverage_service/simple_output_spec.rb

This adds the flag `--teamcity` and then within the `simple_output` coverage service it leverages the [default build statistics for coverage](https://confluence.jetbrains.com/display/TCDL/Custom+Chart#CustomChart-listOfDefaultStatisticValues) to [report](https://confluence.jetbrains.com/display/TCDL/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildStatistics) the results to TeamCity, a continuous integration server by JetBrains.
Example usage would be:
```sh
$ slather coverage --teamcity -s
```
We also can consider cherry-picking [joshrlesch's commit](https://github.com/hudl/slather/commit/4a101fdd315f41aa4ad80289230d7ef04ffc2965) from [PR 132](https://github.com/SlatherOrg/slather/pull/132) which adds support for TeamCity within the `coverall` …

Build Statistic Reporting for TeamCity

---

CHANGELOG.md
lib/slather/project.rb

Update xctest_bundle using the search_for variable. Before xctest_bundle would be set to the first xctest bundle in the build products, even if we're searching for a different test target.
For example, a command such as:
slather coverage --scheme MyScheme --binary-basename BTests --html MyProject.xcodeproj
Would pick ATests over BTests if there are test targets for ATests and BTests, because ATests would always be the first path returned in the initial assignment.

Fix for not being able to find some xctest bundles

---

CHANGELOG.md
lib/slather/project.rb

This fixes #125. profdata_coverage_dir first tries the Xcode 7.2.1 paths, then falls back to the new Xcode 7.3 path if the 7.2.1 path isn't found.
I did not update the tests in `project_spec.rb`. The expected output on lines 452 and 453 will need to be updated when the CI is moved up to Xcode 7.3.

Updated profdata_coverage_dir to work with Xcode 7.3

---

.travis.yml
CHANGELOG.md
lib/slather/project.rb
spec/slather/project_spec.rb

More fixes to improve Xcode 7.3 operability. This may make the automatic binary lookup behavior with Xcode 7.2.1 not work as smoothly, but I haven't tested against 7.2.
This change reads info from the xcodeproj and xcscheme files, so having shared schemes is necessary for things to work smoothly.
Explicitly specifying a scheme in the slather config file or with the `--scheme` argument is also necessary to get the newer path detection. Calling slather without an explicit scheme will still use the old behavior and won't be very reliable.
Because the scheme name is no longer included in directories with Xcode 7.3, using a glob to find the right coverage directory no longer works reliable if you start from the base DerivedData directory. So instead of starting at …

Additional Xcode 7.3 compatibility improvements

---

CHANGELOG.md
README.md
lib/slather/command/coverage_command.rb
lib/slather/project.rb
slather.gemspec
spec/fixtures/fixtures.xcodeproj/xcshareddata/xcschemes/fixtures.xcscheme
spec/fixtures/fixtures.xcodeproj/xcshareddata/xcschemes/fixturesTests.xcscheme
spec/fixtures/fixtures.xcworkspace/contents.xcworkspacedata
spec/slather/cocoapods_plugin_spec.rb
spec/slather/project_spec.rb
spec/spec_helper.rb

* Support for building with Xcode workspaces. Specify `--workspace` or add `workspace` to `.slather.yml` if you run tests in a workspace. This will fix #175 (and is probably the cause of #171, #162, and #154).
* slather errors are printed separately from the exception backtrace, which makes them look a bit less scary. More troubleshooting suggestions are included when there's an error. Fixes #8.
* Added an error if someone specifies a scheme that can't be found (or if it isn't a shared scheme).
* Updated the readme to mention workspaces and to encourage specifying a scheme to get the more accurate coverage detection.
* Fixed code coverage covering the files in `spec` and ignoring the ones `lib` (this means the coverage percentage is going to decrease).
This can be split into multiple pull …

Workspace support and better error messages

---

CHANGELOG.md
lib/slather/profdata_coverage_file.rb
spec/slather/profdata_coverage_spec.rb

llvm-cov prints thousands as 25.3k and millions as 3.8M which requires an additional regular expression to handle them. They were being shown as no coverage before.
Fixes #161.

Support thousands and millions of hit lines with llvm-cov.

---

CHANGELOG.md
lib/slather/project.rb

Since those values are potentially needed for `configure_build_directory`, they need to be configured before it is.

Fix scheme/workspace configuration

---

CHANGELOG.md
lib/slather/profdata_coverage_file.rb
spec/slather/profdata_coverage_spec.rb

Previously (in #179), hit counts in the thousands or millions were output as floats and lower hit counts were output as integers.  This change makes all hit counts consistent.

Output thousands and millions of hits as integers

---

CHANGELOG.md
lib/slather/project.rb
spec/fixtures/fixtures.xcworkspace/xcshareddata/xcschemes/fixturesTestsWorkspace.xcscheme
spec/spec_helper.rb

Add support for searching Xcode workspaces for schemes. Workspaces are checked if no matching scheme is found in the project.
Fixes #191.

Search xcworkspaces for schemes

---

lib/slather/project.rb
spec/fixtures/fixtures.xcworkspace/xcshareddata/xcschemes/fixturesTestsWorkspace.xcscheme
spec/slather/project_spec.rb

configure_binary_file was ignoring binary_file and calling find_binary_file even if binary_file was defined manually.
Also fixed the xcodebuild command for fixtureTestsWorkspace showing an error when running the tests.

Fix for binary-file argument sometimes getting ignored

---

CHANGELOG.md
lib/slather/command/coverage_command.rb
lib/slather/profdata_coverage_file.rb
lib/slather/project.rb
spec/slather/profdata_coverage_spec.rb
spec/slather/project_spec.rb

This PR addresses some issues we had to overcome to make Slather work (well) with our test setup at PSPDFKit. 
See the commit message for details but the essential part is:
>Added a way to specify source file filters.
>- Uses ruby’s Dir.glob for maximum flexibility and easy lookup.
>- Files are passed to llvm-cov to speed up processing. 
>- If ignore patterns are also given, they are applied before the files are passed to llvm-cov so ignored files are not processed at all. 
>- If multiple binaries are processed, the already processed files get excluded during subsequent runs, speeding up processing, if there is a lot of overlap between the binaries.
For our relatively complex test setup where we have multiple test projects covering multiple libraries with quite a bit of overlap between …

Support for specifying llvm-cov source files

---

CHANGELOG.md
lib/slather/profdata_coverage_file.rb
spec/slather/profdata_coverage_spec.rb

Added pattern to match line numbers when llvm-cov output includes thousands as 25.3k and millions as 3.8M

Fix for Corrupted cobertura file format #196

---

CHANGELOG.md
lib/slather/command/coverage_command.rb
lib/slather/coverage_service/html_output.rb
lib/slather/coverage_service/simple_output.rb
lib/slather/project.rb
spec/slather/project_spec.rb
spec/spec_helper.rb

.to_f is used to avoid excessive zeros.
0.0000.to_f => 0.0
Fix #205

Add --decimals flag for HTML and simple output

---

CHANGELOG.md
lib/slather/command/coverage_command.rb
lib/slather/coverage_service/coveralls.rb
spec/slather/coverage_service/coveralls_spec.rb

Added --travispro flag

---

CHANGELOG.md
lib/slather/project.rb
spec/slather/project_spec.rb

Fixes an incorrect fallback value for `input_format` and adds test cases for `configure_input_format` (See #232)

Fixes #232

---

CHANGELOG.md
lib/slather/project.rb
lib/slather/version.rb

Hi,
We are using Slather in a fairly bespoke CI environment where unfortunately it's occasionally been hanging indefinitely when shelling out to xcodebuild. This PR implementation tweak using Open3.popen2e seems to fix the issue for us; we've not seen a single hang since making the change. However, I'm by no means a Ruby stream / I/O expert so if someone could suggest a better implementation I'll very happily adopt it.
I don't believe this change introduces any problems - certainly existing specs all still pass - but I'd appreciate it if others could give it a test too. I've not added any new specs to cover this as it's a pretty non-functional change, but happy to look into that if required.
Many thanks,
Arthur
EDIT - Forgot to mention, I'm pretty sure my version does not suppress STDERR …

Invoke xcodebuild with CODE_SIGNING_* flags to avoid hanging

---

lib/slather/project.rb
spec/fixtures/fixtures/fixtures.m
spec/fixtures/fixtures_html/fixtures.m.html
spec/slather/coverage_file_spec.rb

Fix bad UTF-8 encoding issues

---

README.md

The current Codecov bash script automatically searches in the DerivedData directory for code coverage files (both gcov and profdata files). In order to prevent the codecov script to automatically search for coverage data and generate reports, we disable report generation (-X coveragepy -X gcov -X xcode) and tell it to upload the report generated by slather (-f path/to/xml_report/cobertura.xml).

Update Codecov instructions

---

.travis.yml
CHANGELOG.md
lib/slather/profdata_coverage_file.rb
spec/slather/profdata_coverage_spec.rb

Three small changes:
- Stop using deprecated `Fixnum`
- Use a regex to filter out all files in Xcode platform SDKs. Eliminates the need for practically everyone to ignore `../*`
- Use Xcode 8.2 on Travis to keep up with the times

Automatically ignore headers inside Xcode SDKs. Run Travis tests on Xcode 8.2

---

lib/slather/coverage_service/coveralls.rb
spec/slather/coverage_service/coveralls_spec.rb

When uploading to coveralls, want the option to set `teamcity` as the `ci_service`.
Also added some outputs to help see whats going on in the build log of teamcity.

Add teamcity as a CI service option

---

.travis.yml
CHANGELOG.md
lib/slather/coverage_service/html_output.rb
lib/slather/profdata_coverage_file.rb
lib/slather/project.rb
slather.gemspec
spec/slather/coverage_service/html_output_spec.rb
spec/slather/profdata_coverage_spec.rb

llvm-cov in Xcode 8.3 arbitrarily swapped the line numbers and coverage count. This detects the version of llvm-cov and behaves accordingly.
It'd be good to get a set of eyes on this and do a release if nobody runs into trouble, since Xcode 8.3 is now out (@neonichu in particular, since you've been doing the releases :heart:).

Xcode 8.3 support

---

lib/slather/project.rb
spec/fixtures/fixtures.xcodeproj/project.pbxproj
spec/fixtures/fixtures.xcodeproj/xcshareddata/xcschemes/aggregateFixturesTests.xcscheme
spec/fixtures/fixtures.xcodeproj/xcshareddata/xcschemes/fixturesTestsSecond.xcscheme
spec/fixtures/fixturesTests/fixturesTestsSecond.m
spec/slather/project_spec.rb
spec/spec_helper.rb

Currently (in 2.3.0) it's impossible to slather multiple build action entries of a scheme - only the first one is processed.

Fix for xcode scheme containing multiple testable targets.

---

CHANGELOG.md
README.md
lib/slather/command/coverage_command.rb
lib/slather/project.rb
spec/slather/project_spec.rb

`No product binary found` error occurs when a unit test is executed using a configuration value that is different from the value set in its Xcode project.
`Debug`
```
lane :unittest do
scan(
clean: true,
workspace: "sample.xcworkspace",
scheme: "sample_demo",
configuration: "sample_configuration",
code_coverage: true
)
end
```
```
$ slather coverage --scheme sample_demo --workspace sample.xcworkspace -v sample.xcodeproj
Slathering...
No product binary found in /Users/testuser/Library/Developer/Xcode/DerivedData/sample_demo-drulcbjceghbnoeyoatkqldemoja/Build/Intermediates/CodeCoverage.
Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
If …
```

add configuration option

---

CHANGELOG.md
lib/slather.rb
lib/slather/project.rb
slather.gemspec

slather was using mdls/Spotlight to detect Xcode's version. If mdls returned (null) then the Xcode version was detected as 0, which would cause it to use the gcov path by default.
This changes it so we read the Xcode version out of the plist directly.
This should fix issues like #297 where Spotlight hasn't indexed yet. It will likely fix issues like #262 as well.

Don't use Spotlight for Xcode version detection

---

CHANGELOG.md
lib/slather/project.rb
spec/slather/project_spec.rb

Print a message saying no binary files were found instead of throwing an exception.

Better verbose message when no binaries are found

---

lib/slather/project.rb

I forgot to fix the help message for configuration option.
```
$ slather version
slather 2.4.1
$ slather coverage --scheme sample --workspace sample.xcworkspace -v sample.xcodeproj
Slathering...
No product binary found in /Users/sampleuser/Library/Developer/Xcode/DerivedData/sample-drulcbjceghbnoeyoatkqldemoja/Build/Intermediates/CodeCoverage.
Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
```
```
$ slather coverage --scheme sample --workspace sample.xcworkspace -v sample.xcodeproj
Slathering...
No product binary found in …
```

Added help message for configuration

---

lib/slather/coverage_service/coveralls.rb

I received the following crash:
```Users/Shared/Jenkins/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.4.1/lib/slather/coverage_service/coveralls.rb:41:in `jenkins_branch_name': undefined method `include?' for nil:NilClass (NoMethodError)```
Seems like Slather is currently using GIT_BRANCH_NAME to detect the current branch name, which is unavailable in the Pipeline flow, as mentioned in this [jenkins issue](https://issues.jenkins-ci.org/browse/JENKINS-35230?focusedCommentId=288295&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-288295).
This PR allows Slather to select either of the 2, with GIT_BRANCH being checked first.

Jenkins_branch_name updated for Jenkins' pipeline support

---

lib/slather/project.rb

This addresses issue #306 and fixes Slather for Xcode 7 builds
The main issue is line 239 (https://github.com/SlatherOrg/slather/blob/master/lib/slather/project.rb#L239) of `project.rb`, which parses the LLVM version from the output of `xcrun llvm-cov --version`. If the version can't be parsed, the match array is null, and the `captures` method fails. The stack trace returns:
/usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.1/lib/slather/project.rb:239:in `configure': undefined method `captures' for nil:NilClass (NoMethodError)
from /usr/local/lib/ruby/gems/2.4.0/gems/slather-2.4.1/lib/slather/command/coverage_command.rb:53:in `execute'
from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
from /usr/local/lib/ruby/gems/2.4.0/gems/clamp-0.6.5/lib/clamp/subcomm …

Retrieving LLVM version is now backwards compatible with Xcode 7

---

lib/slather/project.rb

Additional Xcode 9 support (thank you to #321 and #338).
Most of the tests pass when run against Xcode 9, but 4 tests still fail due to expecting Xcode 8's directory layout. These tests can be updated once Travis is switched over to Xcode 9.

Xcode 9 support

---

lib/slather/project.rb

Sometimes, Slather returns "No product binary found" while there's one in the build dir... 
After a debug session it appears that the "first" found_product is the .swiftmodule and not the .app.
Excluding it like the .dSYM get it working again !
Closes #347

exclude swiftmodule from Product search

---

lib/slather.rb
lib/slather/command/coverage_command.rb
lib/slather/coverage_service/llvm_cov_output.rb
lib/slather/project.rb
spec/fixtures/report.llcov
spec/slather/coverage_service/llvm_cov_spec.rb
spec/spec_helper.rb

This is the raw per-line output from `llvm-cov show`, required by SonarQube's SonarSwift plugin.

Support for llvm-cov output format. Only supports Profdata input.

---

.travis.yml
CHANGELOG.md
README.md
lib/slather/command/coverage_command.rb
lib/slather/project.rb
spec/slather/project_spec.rb

Based on #346 (and #362).
There's now an `arch` argument or config option to specify what architecture the binary is in. This argument is used by `find_binary_files` and passed to `llvm-cov` so universal binaries use the right architecture.
I believe this will fix #353 as well.

Support for specifying a specific binary architecture

---

lib/slather/project.rb

`search_list.each ... .reject` doesn't work **at all** due to incorrectly written multiline `reject` block. On my project slather crashes trying to call `split` on `nil` and apparently it allowed to pass `.dSYM` paths to `matches_arch` function.
I noticed this issue when I built an app using **Debug** configuration for **Generic iOS Device**. After that slather crashed trying to `lipo nil` because `.dSYM` is a folder and `find_binary_file_in_bundle` returned `nil` for it.
Simplified demo on current implementation and two ways to write that right: https://repl.it/repls/BonyConsiderateModel

Fix .dSYM and .swiftmodule files filtering in find_binary_files()

---

lib/slather/profdata_coverage_file.rb

Fixing #376 issue.
`“    1|      <NUMBER>|<CODE>”` line (corresponds to Xcode 9.3 `xcrun llvm-cov show` output) should be detected as `!path_on_first_line?`. Previous `path_on_first_line?` implementation returns `true` for that example failing to process single source binary.

Fix single source file in binary predicate

---

lib/slather/project.rb
spec/slather/coverage_service/coveralls_spec.rb
spec/slather/coverage_service/hardcover_spec.rb
spec/slather/project_spec.rb

When binary contains single source file, output of `llvm-cov show` does not contain the file name. That leads to `source_file_pathname` to contain actual source code (first line of it) instead of a path.
Previously, result of `find_source_files` method was used to understand if a binary is a single source:
```
source_files = find_source_files || []
…
coverage_file.source_file_pathname = source_files.first if source_files.count == 1
```
Though that approach won’t work for projects which contains several binaries (and then `source_files` will be a mix of files from different binaries) or when you don’t provide list of source file in configuration (it’s what `find_source_files` returns). So we either need to provide the list of files per binary or somehow get the info from profdata file. …

Use `llvm-cov export` to detect source files per binary

---

CHANGELOG.md
lib/slather/version.rb
slather.gemspec

Updates slather dependencies, including dev and runtime; also verified that all unit tests pass after update.

Updates slather dependencies, including dev and runtime.

---

slather.gemspec

Fixed warnings re: dependency versions: coveralls, simplecov, CFPropertyList were open ended.

Fixed warnings re: dependency versions

---

lib/slather/project.rb
spec/slather/project_spec.rb

I have encountered the issue in https://github.com/SlatherOrg/slather/issues/243 which is not easily solvable. This is an attempt to fix the problem by chunking calls llvm cov into smaller segments which are recombined. I'll give it some time to see if there are any problems.

Chunk pathnames_per_binary into segments that do not exceed the OS ARG_MAX size for calls to llvm-cov

---

README.md

Hello, I was configuring my project with multiple targets and was expecting coverage data for all targets (using `.slather.yml`)
After a lot of debugging and reading source code I found that readme had a typo :)
https://github.com/SlatherOrg/slather/blob/25ebacbd1ddcb5494beee753af4046460f7e93d5/lib/slather/project.rb#L457-L459

Fix `binary_basename` configuration key

---

spec/slather/cocoapods_plugin_spec.rb

CocoaPods plugin got updated, and installed version (1.8.4) now accepts three arguments for generating
https://github.com/CocoaPods/CocoaPods/blob/21adb0c6664022428cbb742e5bd6abfa55f274e5/lib/cocoapods/installer/post_install_hooks_context.rb#L38-L62
This pull request fixes it by just passing mocked project file into generator method

Fix `spec/slather/cocoapods_plugin_spec.rb` spec

---

slather.gemspec

Hello, I found that coveralls gem isn't properly set.
Thus it is failing to upload coverage data to coveralls.
This pull request adds explicit coveralls dependency version, so it can properly use simplecov gem and upload to coveralls

Update coveralls gem to match simplecov

---

lib/slather/profdata_coverage_file.rb
spec/slather/profdata_coverage_spec.rb

There is already a PR open since May 2018 for this problem: https://github.com/SlatherOrg/slather/pull/387
The issue is still valid when passing the XML to `sonar-scanner`.
I changed a few minor things compared to the original PR and I also included some test cases. I had troubles running all tests locally, hopefully this meets the coverage expectations.

Don't generate line 0 in profdata_coverage_file.rb from line with error

---

lib/slather.rb
lib/slather/command/coverage_command.rb
lib/slather/coverage_service/sonarqube_xml_output.rb
lib/slather/project.rb
spec/fixtures/sonarqube-generic-coverage.xml
spec/slather/coverage_service/sonarqube_xml_spec.rb
spec/spec_helper.rb

Hello 👋 
This PR add support for Sonarqube generic code coverage xml. 😄
I am not sure what's the policy for adding new output strategy, I hope this could fit in. 🙏 
Cheers,
Edited: probably this closes #258

Add support for Sonarqube generic code coverage output

---

lib/slather/version.rb
slather.gemspec

These seem to have come from our downstream dependency, cocoapods, and
they have dropped the activesupport constraint in order to inherit it
from the core project.
Issue number: #465

Remove activesupport constraints

---

README.md
lib/slather/command/coverage_command.rb
lib/slather/coverage_service/coveralls.rb
spec/slather/coverage_service/coveralls_spec.rb

As I needed the Github actions working for slather and coveralls I have used #459 as a base to start debugging and to find the problem. I have sent an email to coveralls support and they have answered that for github actions they are not using the coveralls repo secret, but they are using the `GITHUB_TOKEN` env secret from github actions. I have implemented that change and also I have added some more useful env variables for the report generation.
As a result the reports are working correctly using slather with github actions and coveralls. 
- #459 (thanks @troyfontaine)
- https://github.com/marketplace/actions/coveralls-github-action 
- https://docs.coveralls.io/api-reference 
- All the commits has been squashed
- PR may be merged with Squash and merge for clean description and reference …

Implementing Github Actions

---

README.md
spec/slather/coverage_service/coveralls_spec.rb

Here is the fix for github actions tests. I would suggest removing the commit for Slather 2.6.0 then merging this PR and making the commit again. 
It will be positive to update to the latest bundler version at some point and fixing the tests because on Bundle 2.1.4 there are few errors that need to be resolved.

Fixing the tests for github actions

---

slather.gemspec

Nokogiri < 1.11 is vulnerable to XML External Entity (XXE) Injection 
https://snyk.io/vuln/SNYK-RUBY-NOKOGIRI-1055008

Update nokogiri to 1.11

---

lib/slather/project.rb

POSIX systems have an `ARG_MAX` for the maximum total length of the command line, so the command may fail with an error message of "Argument list too long". This is happening in some cases when running Slather, as reported in #431. 
This error is happening when executing `xcrun llvm-cov` for a large list of source files. 
The solution is to use `xargs`. Using this command we can break the list of source_files into sublists small enough to be acceptable. `xargs` uses spaces as delimiters for params. To avoid issues with paths containing spaces `xargs` is used with `-0` argument:
```bash
printf '%s\\0' #{source_files.shelljoin} | xargs -0 xcrun llvm-cov #{llvm_cov_args.shelljoin}
```

Fixed 'Argument list too long' when running 'xcrun llvm-cov' 

---

lib/slather/profdata_coverage_file.rb
spec/slather/profdata_coverage_spec.rb

This PR is intended to fix #481
If we want `[[a,b],[c,d]]` from `[[a,b]]` and `[c,d]`, we should use `<<`.

Fix for multiple region data

---

lib/slather/coverage_service/html_output.rb

This PR is intended to fix #480 
If `line` is `"if(_var && _var.foo) {"` and `regions` is `["_var", "_var.foo", "{"]`, 
After the first loop,
expected:
`reminder` should be `" && _var.foo) {"`
actual:
`reminder` is `" && "`

Consider the case where multiple phrases appear in line

---

lib/slather/project.rb
spec/fixtures/FixtureFramework/FixtureFramework.h
spec/fixtures/FixtureFramework/FlashExperiment.swift
spec/fixtures/FixtureFramework/Info.plist
spec/fixtures/FixtureFrameworkTests/FixtureFrameworkTests.swift
spec/fixtures/FixtureFrameworkTests/FlashExperimentTests.swift
spec/fixtures/FixtureFrameworkTests/Info.plist
spec/fixtures/fixtures.xcodeproj/project.pbxproj
spec/fixtures/fixtures.xcodeproj/xcshareddata/xcschemes/fixtures.xcscheme
spec/fixtures/fixtures.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
spec/slather/project_spec.rb

This PR enables code coverage from framework targets to be extracted.
Issue: #432
This should also take care of #440.

Extract the framework target binaries from the CodeCoverageTargets.

---

lib/slather/coverage_service/html_output.rb

In the project where multiple modules are created, having just the code coverage percentage per module is not enough information to calculate the overall code coverage for the whole project. Additional information about total number of lines and total number of lines tested is required.
In this PR additional data regarding total number of lines and total number of lines tested is added to html report.

Add relevant lines count and tested lines count to html report

---

slather.gemspec

There is a high severity warning about versions of nokogiri lower than 1.12.5. The GitHub report can be found here: https://github.com/advisories/GHSA-2rr5-8q37-2w7h
This pull request bumps the dependency to 1.12, allowing the fixed 1.12.5 version to be used.

Bump nokogiri version

---

slather.gemspec

👋 Hi there!
Between CocoaPods and Fastlane using more recent versions of xcodeproj I’m blocked from using Slather 2.7.1, the latest release.
This PR just bumps Slather’s xcodeproj dependency from 1.7 to 1.21. Easy peasy.
Let me know if there’s documentation or versioning or anything else I should add here. Thanks!

Bump xcodeproj to 1.21

---

lib/slather/coverage_service/coveralls.rb
lib/slather/project.rb

According to [Coveralls Docs](https://docs.coveralls.io/supported-ci-services), you can _INSERT YOUR CI HERE_ by exporting from the CI server the following variables:
```
CI_NAME
CI_BUILD_NUMBER
CI_BUILD_URL
CI_BRANCH
CI_PULL_REQUEST (optional)
```
This PR takes those variables from the environment and sets `:unknown` as the default `ci_server`

Support "other" CI servers

---

lib/slather/coverage_service/coveralls.rb
lib/slather/project.rb

Changes:
* Adding `git` info to `:other` `ci_service`.
* Letting `slather` take `ci_service` not only from `.slather.yml` but from the environment `$CI_SERVICE`
* Adding support for `Bitrise`

Bitrise Coveralls support

---

lib/slather/coverage_service/coveralls.rb

add IS_PARALLEL environment to allow parallel
and `flag_name` as GitHub job name
> parallel | *Boolean* OPTIONAL If this is set, the build will not be considered done until a webhook has been sent to https://coveralls.io/webhook?repo_token=…
> -- | --
> flag_name | *String* OPTIONAL If this is set, the job being reported will be named in the view and have it’s own independent status reported to your VCS provider.
>

support Coveralls parallel runs

---

lib/slather/coverage_file.rb
lib/slather/project.rb
spec/slather/coverage_service/cobertura_xml_spec.rb
spec/slather/coverage_service/json_spec.rb
spec/slather/coverage_service/llvm_cov_spec.rb
spec/slather/coverage_service/sonarqube_xml_spec.rb

- `File.exists?` has been deprecated since Ruby 2.1.0.
- and [ruby@3.2 removed File.exists?](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/), therefore Slather is now failing, when using ruby@3.2
- Fixes https://github.com/SlatherOrg/slather/issues/529
- I basically searched for all occurrences of File.exists? and
- Now start using `File.exist?`

Start using `File.exist?` for deprecated `File.exists?` which got removed in ruby@3.2

---

README.md
lib/slather/command/coverage_command.rb
lib/slather/coverage_service/html_output.rb
lib/slather/project.rb
lib/slather/version.rb

I have worked on a few projects that use slather in the last few years. I have always accepted that the HTML report viewing experience will be sub-par because there are no CSS and JS files once the report (index.html) is deployed to Azure DevOps or Bitrise (I'm sure others have similar limitations).
I propose that instead of referencing the local`logo.jpg`,`list.min.js, `highlight.pack.js` and `slather.css` relative to the HTML report, the report should instead reference a Web/CDN version. This way HTML reports will be feature-rich when deployed to these services as build artifacts.
1. No change in default behavior. The new flag is opt-in.
2. Reads slather logo, CSS and JS from the master branch of SlatherOrg GitHub project using jsdelivr CDN. Could consider making it more dynamic and …

Adding `--cdn-assets` flag that loads the Logo, CSS and JS files from jsdelivr CDN

---

README.md

- Update the documentation, explaining how to set the CI service
- I wasted a few hours trying to get Coveralls working, because the documentation didn't say anything about `ci_service`, and the default integration was partially working.
- I would like to prevent other people wasting their time as well

Update README.md with ci_service

---

README.md
lib/slather/command/coverage_command.rb
lib/slather/coverage_info.rb
lib/slather/profdata_coverage_file.rb
lib/slather/project.rb

This update introduces a mechanism that handles the globs specified in the source_files configuration.
* It adds new functionality to include source files matching the specified glob patterns and allows the configuration of these source files. Files not matching a glob defined in `source_files` are excluded.
* Additionally, it refactors the ignored file code in the profdata_coverage_file class to streamline the condition checks.
At it's most basic, the file is checked to see if it's ignore and, if it isn't and there are source_files defined, tested to see if it should be included in the scan.

chore: handle include globs

---

lib/slather/coverage_service/cobertura_xml_output.rb
spec/fixtures/cobertura.xml

Use `https` when writing the dtd link to the cobertura.xml file. Fixes #558

Fix #558: cobertura.sourceforge.net should use https instead of http.

---

CHANGELOG.md
lib/slather/coverage_info.rb

`coverage_info.include_files?` needs a default `true` return value for when source_files is empty.

fix #561: Set a default true return value for when source_files is empty.

---

.gitignore
CHANGELOG.md
lib/slather/coverage_service/cobertura_xml_output.rb

`https://cobertura.sourceforge.net/xml/coverage-04.dtd` 404s, so any tool that tries to actually validate the xml with the dtd will fail.
`https://raw.githubusercontent.com/cobertura/cobertura/master/cobertura/src/site/htdocs/xml/coverage-04.dtd` is the file that used to be published to SourceForge but still exists. 
Output cobertura.xml validate now with the new url.

Fix #558 404 dtd url

---

slather.gemspec

Hello,
Xcodeproj recently published a new version that adds [support to Xcode 16 new folder project structure](https://github.com/CocoaPods/Xcodeproj/pull/985).
Before that, we faced some issues when trying to generate reports with an Xcode project that used the new Folder structure. 
Thanks!

Update Xcodeproj to 1.27.1
