- .coveralls.yml
- spec/slather/coverage_service/coveralls_spec.rb
As suggested: https://github.com/lemurheavy/coveralls-public/issues/465
> Stop overwriting TRAVIS_JOB_ID env variable

- spec/slather/coverage_service/coveralls_spec.rb
> Reintroduce travis_job_id test

- Rakefile
- spec/spec_helper.rb
Hoping to solve https://github.com/venmo/slather/pull/52#issuecomment-76005724 but waiting for travis to confirm
> Load coveralls before application code

- README.md
> Update CircleCI link

- README.md
I can’t even with the blurriness.
> [README.md] Use svg Coveralls badges

- lib/slather.rb
- lib/slather/coverage_service/hardcover.rb
- lib/slather/project.rb
- spec/slather/coverage_service/hardcover_spec.rb
*The other one became to messy.*
Hardcover is a new awesome in-house alternative to coveralls. We have been using it for the past 3 months internally and finally open sourced it.
For it to succeed we need this little PR merged into it.
You can find detailed information on how it works here: https://github.com/xing/hardcover#slather
Thanks for the good work, slather was a key for this project to work.
:dancer:
> Add hardcover as a service

- README.md
@marklarr great README! I tried to improve a couple things, let me know if you agree it makes things a bit clearer.
> Tried to make a couple things clearer

- lib/slather/coverage_service/hardcover.rb
- spec/slather/coverage_service/hardcover_spec.rb
> Fix yml method call

- README.md
As per #81 adding Codecov to the readme. Thanks!
> Update readme to support Codecov

- README.md
- bin/slather
- removing `-h` flag to prevent confusion for `--help`
- updating the docs accordingly (plus add `--show` flag)
- updating my github link
> Housecleaning the docs

- README.md
CGFloatType no longer uses slather.
> Remove CGFloatType as an example from the README

- lib/slather/coverage_service/html_output.rb
- spec/fixtures/fixtures_html/Branches.m.html
- spec/fixtures/fixtures_html/fixtures.m.html
This commit provides a fix for #122 and corrects a couple of the test fixtures that were masking the issue when running the tests.
> Correct html rendering when using profdata format

- .travis.yml
- Rakefile
- lib/slather/project.rb
- slather.gemspec
- spec/slather/coverage_file_spec.rb
- spec/slather/coverage_service/coveralls_spec.rb
- spec/slather/coverage_service/hardcover_spec.rb
- spec/slather/coverage_service/html_output_spec.rb
- spec/slather/profdata_coverage_spec.rb
- spec/slather/project_spec.rb
As titled, also:
1. Add test coverage files to `.gitignore`
2. Properly set up `Rakefile`
> Update RSpec gem version & test syntax to 3

- CHANGELOG.md
- lib/slather/command/coverage_command.rb
Was accidentally removed by d4bf4b4
Fixes #177
> Re-add Teamcity support

- CHANGELOG.md
- bin/slather
- lib/slather/command/version_command.rb
- lib/slather/project.rb
- lib/slather/version.rb
> Add slather version command

- CHANGELOG.md
- lib/slather/coverage_service/html_output.rb
- lib/slather/project.rb
- spec/slather/coverage_file_spec.rb
- spec/slather/coverage_service/coveralls_spec.rb
- spec/slather/coverage_service/html_output_spec.rb
- spec/slather/project_spec.rb
> API update

- CHANGELOG.md
- lib/slather/coverage_service/coveralls.rb
- spec/slather/coverage_service/coveralls_spec.rb
Improves the error handling for uploads to Coveralls service and avoids configuration errors. Fixes #217
> Improved error handling for Coveralls service

- slather.gemspec
> Losen `xcodeproj` dependency

- lib/slather/coverage_service/simple_output.rb
- spec/slather/coverage_service/simple_output_spec.rb
- spec/slather/project_spec.rb
I added the number of statements on the simple output it was based on https://github.com/ivanbruel/slather/commit/c320eac4307be6347389d8ec5fd9e90b3315a1e6
> Adding statments on simple output

- README.md
I just needed to exclude some Pod targets and found the solution is already merged: https://github.com/SlatherOrg/slather/pull/188.
> Update Readme for multiple modules

- .gitignore
- slather.gemspec
Some vulnerabilities are found on Nokogiri .
Nokogiri is update to '>= 1.13.6'.
> # FIX: Vulnerabilities on Nokogiri
